name: deno-tests
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno
        with:
          deno-version: v1.30.3
      - run: deno run test/*.test.ts
